/** Firing range check: enter range, shoot targets with the autopilot, cycle weapons, screenshot. */
import { chromium } from 'playwright';
const url = process.argv[2] || 'http://localhost:4180/';
const out = process.argv[3] || 'shots';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
p.on('pageerror', (e) => errors.push(e.message + ' ' + (e.stack || '').split('\n')[1]));
p.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('Failed to load')) errors.push(m.text()); });
await p.addInitScript(() => localStorage.setItem('ashline.settings', JSON.stringify({ graphics: { preset: 'medium', renderScale: 0.6, shadows: 'low', textures: 'medium', effects: 'medium', bloom: true, ao: false } })));
await p.goto(url, { waitUntil: 'load', timeout: 120000 });
await p.waitForFunction(() => window.__ashline?.state === 'menu', null, { timeout: 120000 });
await p.click('text=Firing Range');
await p.waitForFunction(() => window.__ashline?.game?.isRange, null, { timeout: 60000 });
let st = await p.evaluate(() => { const g = window.__ashline.game; return { n: g.match.combatants.length, dummies: g.match.combatants.filter((c) => c.dummy).length, map: g.map.def.id }; });
console.log('range', JSON.stringify(st));
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/range-01.png` });
await p.evaluate(() => { window.__ashline.autopilot(true); window.__ashline.game.debugAdvance(12); window.__ashline.autopilot(false); });
await p.evaluate(() => { const a = window.__ashline; for (let i = 0; i < 3; i++) { a.input.poll(); a.game.update(1 / 30); a.input.endFrame(); } });
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}/range-02.png` });
st = await p.evaluate(() => { const g = window.__ashline.game, pl = g.player; return { kills: pl.stats.kills, shots: pl.stats.shots, hits: pl.stats.hits, reserve: pl.weapon.reserve, last: g.range.last, lastKill: g.range.lastKill, panel: document.querySelector('.range-panel').innerText.slice(0, 200) }; });
console.log(JSON.stringify(st));
await p.keyboard.down('KeyT');
const w = await p.evaluate(() => { const a = window.__ashline; a.input.poll(); a.game.update(1 / 30); a.input.endFrame(); return a.game.player.weapon.def.id; });
await p.keyboard.up('KeyT');
console.log('after T:', w);
console.log('errors:', errors.join(' | ') || 'none');
await b.close();
