/**
 * Vault tool for staged content drops.
 *
 *   node tools/vault.mjs keygen                      → print a new release code
 *   node tools/vault.mjs seal <content.json> <code>  → encrypt into src/data/vault.js (replaces an entry with the same id)
 *   node tools/vault.mjs open <code>                 → decrypt and print what a code unlocks
 *   node tools/vault.mjs release <code>              → bake the code into src/data/releases.js (public release build)
 *   node tools/vault.mjs list                        → sealed entries (ids and sizes only)
 *
 * Keep content.json and the code out of the repository until release.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { seal, unseal, normalizeCode } from '../src/core/vault.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const vaultFile = path.join(root, 'src/data/vault.js');
const relFile = path.join(root, 'src/data/releases.js');
const [cmd, a1, a2] = process.argv.slice(2);

const readVault = async () => (await import(vaultFile + '?t=' + Date.now())).VAULT;
const writeVault = (list) => fs.writeFileSync(vaultFile, `/**
 * Sealed content (AES-256-GCM, PBKDF2-SHA256 keys). Generated by tools/vault.mjs —
 * do not edit by hand. Each entry stays unreadable until its release code is
 * supplied; see src/core/vault.js.
 */
export const VAULT = ${JSON.stringify(list, null, 2)};
`);

if (cmd === 'keygen') {
  const A = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = crypto.getRandomValues(new Uint8Array(20));
  const s = [...bytes].map((b) => A[b % A.length]).join('');
  console.log(`${s.slice(0, 5)}-${s.slice(5, 10)}-${s.slice(10, 15)}-${s.slice(15, 20)}`);
  console.log('(~100 bits of entropy; keep it private until release)');
} else if (cmd === 'seal') {
  if (!a1 || !a2) { console.error('usage: seal <content.json> <code>'); process.exit(1); }
  const payload = JSON.parse(fs.readFileSync(a1, 'utf8'));
  if (!payload.vaultId) { console.error('content.json needs a "vaultId"'); process.exit(1); }
  if (normalizeCode(a2).length < 16) { console.error('code too short — use "keygen"'); process.exit(1); }
  const entry = await seal(payload.vaultId, payload, a2);
  const list = (await readVault()).filter((e) => e.id !== entry.id);
  list.push(entry);
  writeVault(list);
  const back = await unseal(entry, a2);
  console.log(`sealed "${entry.id}" (${entry.data.length} b64 chars) — verify ${back ? 'OK' : 'FAILED'}`);
} else if (cmd === 'open') {
  let any = false;
  for (const e of await readVault()) { const p = await unseal(e, a1); if (p) { any = true; console.log(`${e.id}:`, JSON.stringify(p, null, 2)); } }
  if (!any) { console.log('this code opens nothing'); process.exit(1); }
} else if (cmd === 'release') {
  let ok = false;
  for (const e of await readVault()) if (await unseal(e, a1)) ok = true;
  if (!ok) { console.error('this code opens nothing — not released'); process.exit(1); }
  const cur = (await import(relFile + '?t=' + Date.now())).RELEASE_KEYS;
  const n = normalizeCode(a1);
  const list = [...new Set([...cur, n])];
  fs.writeFileSync(relFile, `/** Release codes baked into this build (public releases). Managed by tools/vault.mjs. */\nexport const RELEASE_KEYS = ${JSON.stringify(list)};\n`);
  console.log('released in this build — rebuild and deploy');
} else if (cmd === 'list') {
  for (const e of await readVault()) console.log(`${e.id}  ${e.data.length} b64 chars  pbkdf2 ${e.iter}`);
} else {
  console.log('commands: keygen | seal <content.json> <code> | open <code> | release <code> | list');
}
